### ISSUE TITLE
[CRASH] I have found the first error! yay

### ISSUE THREAD

**Issue by OneBakaBoi** [Rebirth-of-the-Night/onslaught#1]
Installed the mod into my modpack, and also installed it on its own and I got this: [crash report](https://pastebin.pl/view/38b5aa2a)

**Comment by codetaylor** [comment]
It requires this library mod: https://www.curseforge.com/minecraft/mc-mods/athenaeum

**Comment by codetaylor** [comment]
That should probably be set up as a dependency on CurseForge.

**Comment by CalaMariGold** [comment]
I added it to the description. Sorry about that

**Comment by codetaylor** [comment]
I added it as a dependency to the file so it will be auto-downloaded. :)
