### ISSUE TITLE
[Issue/Suggestion] Can blocks broken during a raid be "replaced" over time, like with HW Invasions?

### ISSUE THREAD

**Issue by ghost** [Rebirth-of-the-Night/onslaught#12]
This mod is truly incredible, and so so so much easier to use than HW Invasions.

However, two major things are missing that do not allow this mod to be superior:

1.  No Hoist AI
2. Blocks broken during a raid are truly broken.

One of the greatest parts of the HW Invasions Mod is that blocks broken during a raid by creeper explosions, miner mobs, and player explosions are "replaced" over a 5 minute period of time. It makes the game so enjoyable.

Is there any way to do something similar for this mod?

**Comment by Dillsfawn** [comment]
If this is implemented please make a config option to disable it. I did not like that feature of HW Invasions and was thankful it could be disabled.

**Comment by SekretOne** [comment]
> * No Hoist AI

Opening as a separate request #

**Comment by SekretOne** [comment]
> No Hoist AI

Splitting off this request to consider it separately.

**Comment by SekretOne** [comment]
At this time, I don't think `Blocks repairing` it's in the spirit or scope of this particular pack. In future, will look into ways to provide hooks for such behavior.

Instead, we'll focus on ways to configure invasions to get to you without being hyper destructive to the environment (unless you want your invaders to do that)

Track #16 for the Hoist AI- as that would be a perfect example of such an option.
