### ISSUE TITLE
[Issue/Suggestion] Air spawnType spawns mobs on the ground.

### ISSUE THREAD

**Issue by Dillsfawn** [Rebirth-of-the-Night/onslaught#13]
Air spawnType spawns mobs on the ground. rangeY has no bearing either, the mob is always spawned on the ground.
The Air spawnType should always spawn the mob in the air at the specified height. Even if the mob is not a flying or floating mob. 
Sometimes you just want it to rain Creepers.

EDIT: I've looked closer at the github code, and it seems the mobs are spawned close to the player's Y position, and rangeY is a randomization of Y position rather than an offset. This makes it impossible to force mobs to intentionally spawn mobs above or below the player. I think an Y offset option would be very useful here.

**Comment by SekretOne** [comment]
This will take some considering. The spawning mechanics need a bit more control, but need to be convenient. I think the enemies should spawn:

1. Always at some horizontal distance (so they 'come' from somewhere)
2. waves have a 'height' preference
    3. normal: `default`: mobs try to spawn at approximately the same Y height
    4. above: prefer higher than the player say ~10 blocks up
    5. below: prefer lower than the player say ~10 blocks down

**Comment by SekretOne** [comment]
It's back in baby.

**Comment by democat3457** [comment]
Closed by #22

**Comment by SekretOne** [comment]
Apparently Solves is not a synonym of resolve.

https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
