### ISSUE TITLE
Skipping entity?

### ISSUE THREAD

**Issue by squidwrad** [Rebirth-of-the-Night/onslaught#23]
I can't figure out why the entity I select gets skipped by the script. It may be that its a non living entity but the discord server said there is a way to load them but I'd have to ask the GitHub for answers. Long story short there's an entity that is a laser from the sky and it does damage. if I use the summon command in minecraft then it summons normally. But the mod just skips right over the entity entirely. If I can receive some help that'd be great 

```json
{
  "Laser show": {
    "name": "glassing the surface",
    "selector": {
      "weight": 1,
      "dimension": {
        "type": "include",
        "dimensions": [0]
      }
    },
    "messages": {
      "start": "They started the purging of the surface? Run and hide!",
      "end": "They'll be back to finish the job",
      "warn": {
        "ticks": 12000,
        "message": "Radar detects multiple high orbit hostile ships above your AO"
      }
    },
    "waves": [
      {
        "delayTicks": [0],
        "groups": [
          {
            "weight": 1,
            "forceSpawn": true,
            "mobs": [
              {
                "id": "laser",
                "count": [12, 16],
                "spawn": {
                  "type": "ground",
                  "rangeXZ": [0,16]
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
```

```json
{
  "laser": {
  "id":"mowziesmobs:solar_beam"
  }
}
```

**Comment by democat3457** [comment]
fyi its triple backticks (\`\`\`)

**Comment by squidwrad** [comment]
wait, what is triple back ticks? I need to know! the file? the question? I need answers

**Comment by democat3457** [comment]
to make a codeblock
this is `inline code` (\`)
```
this is codeblock (```)
```

**Comment by squidwrad** [comment]
I appreciate it, ill adjust the OP

**Comment by democat3457** [comment]
(i already edited the post)

**Comment by squidwrad** [comment]
I appreciate that, also. I'll keep in mind the triple back ticks fro next time.

**Comment by SekretOne** [comment]
I have also edited it. If you put triple backticks and then the language / syntax you get highlighting.

What's your light range here? The default would not let it spawn in the sun.

> it may be that its a non living entity but the discord server said there is a way to load them but I'd have to ask the GitHub for answers.

I wasn't familiar with the entity you were referring to. If you turn on debug in the config, when you spawn do you see any issues in your log?

**Comment by SekretOne** [comment]
[Solar Beam is in fact not a LivingEntity](https://github.com/BobMowzie/MowziesMobs/blob/ae2b0010a1398ffca28419577002b727e9281be6/src/main/java/com/bobmowzie/mowziesmobs/server/entity/effects/EntitySolarBeam.java#L35)

At  this time, Onslaught only supports the creation of Living Entities (things with health that can take AI tasks) so you have something to fight.
