### ISSUE TITLE
Suggestion: serene seasons condition + turning off default fallback invasion

### ISSUE THREAD

**Issue by NebelFox** [Rebirth-of-the-Night/onslaught#28]
Suggestion is to add a condition for invasion templates so invasion can or cannot start during specified sub-seasons. It would allow to make seasons-themed invasions what is, in theory, quite interesting idea.

And in addition. I've read the docs, and had a look at the config file. As I've got, if no invasion can be fired due to their conditions at invasion time, then it falls back to some default invasion. But I didn't see any option to disable it. So it would be nice to make this ability. I'm sorry if it's already implemented.

**Comment by howisthisman** [comment]
Couldn't you achieve the season-based invasions using gamestages, giving the player a "season1-2-3-4" stage each time a season changes? The mod comes with gamestages support, so that's probably not too hard to work out.

**Comment by NebelFox** [comment]
Thanks for response. I'm sorry about my ignorance of such gamestages feature.
