### ISSUE TITLE
Spawning OutOfBounds Crash

### ISSUE THREAD

**Issue by mxnmnm** [Rebirth-of-the-Night/onslaught#30]
https://gist.github.com/mxnmnm/0b1e8151e894d97b892ed351b421a8b4

**Comment by democat3457** [comment]
what invasion was playing

**Comment by mxnmnm** [comment]
Hmmmm I think this might have just been a hiccup when was adding/removing raids and reloading while one of those raids was ongoing. Not a big deal so I'll close the issue
